services:
  access_point:
    build: ./access_point
    container_name: fms_ap
    # TODO: get the networking working and figure out jupyter flow
    expose:
      - "4444"
    networks:
      wepnet:
        ipv4_address: 172.20.0.2
    tty: true

  attacker:
    build: ./attacker
    container_name: fms_attacker
    networks:
      wepnet:
        ipv4_address: 172.20.0.3
    tty: true

  client:
    build: ./client
    container_name: fms_client
    networks:
      wepnet:
        ipv4_address: 172.20.0.4
    depends_on:
      - access_point
    tty: true


networks:
  wepnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
