services:
  access_point:
    build: ./access_point
    container_name: fms_ap
    expose:
      - "4444"
    networks:
      wepnet:
        ipv4_address: 172.20.0.2
    tty: true

  attacker:
    build: ./attacker
    container_name: fms_attacker
    networks:
      wepnet:
        ipv4_address: 172.20.0.3
    depends_on:
      - access_point
    tty: true

  client:
    build: ./client
    container_name: fms_client
    networks:
      wepnet:
        ipv4_address: 172.20.0.4
    depends_on:
      - attacker
    tty: true

  notebook:
    user: root
    build: ./notebook
    container_name: fms_notebook
    networks:
      wepnet:
        ipv4_address: 172.20.0.5
    ports:
      # note accessible from the LAN since we don't use 0.0.0.0:8888
      - "127.0.0.1:8888:8888" 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  wepnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
